andreivscompsci/urls.py
#from django.conf.urls import url
#from django.contrib import admin

#urlpatterns = [
#    url(r'^admin/', admin.site.urls),
#]
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView

from django.conf import settings
from django.conf.urls.static import static
from profiles.views import CustomLoginView

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', TemplateView.as_view(template_name='home_blog.html'), name='home'),
    #url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    #url(r'^test/$', TemplateView.as_view(template_name='test.html'), name='test'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^profile/', include('profiles.urls', namespace='profiles')),
    #url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^login/$', CustomLoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page='/'), name='logout'),

    url(r'^summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url

from .views import (
    ArticleListView,
    AllArticleListView,
    ArticleDetailView,
    ArticleDeleteView,
    ArticleUpdateView,
    ArticleCreateView,

    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView
)

urlpatterns = [
    #url(r'^$', ArticleListView.as_view(), name='list-all'),
    url(r'^$', AllArticleListView.as_view(), name='list-all'),
    url(r'^new-article/$', ArticleCreateView.as_view(), name='article-new'),
    url(r'^new-category/$', CategoryCreateView.as_view(), name='category-new'),
    url(r'^(?P<slug>[-\w]+)/update/$', CategoryUpdateView.as_view(), name='category-edit'),
    url(r'^(?P<slug>[-\w]+)/delete/$', CategoryDeleteView.as_view(), name='category-delete'),
    url(r'^(?P<category>[-\w]+)/$', ArticleListView.as_view(), name='list-specific'),
    url(r'^(?P<category>[-\w]+)/page/(?P<page>\d+)/$', ArticleListView.as_view(), name='list-page'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/update/$', ArticleUpdateView.as_view(), name='article-edit'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/delete/$', ArticleDeleteView.as_view(), name='article-delete'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$', ArticleDetailView.as_view(), name='article-view')
]

profiles/urls.py
from django.conf.urls import url
from .views import ProfileDetailView


urlpatterns = [
    #url(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name='detail')
    url(r'^$', ProfileDetailView.as_view(), name='index')
]

blog/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django_bleach.models import BleachField


class ArticleQuerySet(models.query.QuerySet):
    def search(self, query): #Article.objects.all().search(query) #Article.objects.filter(something).search()
        if query:
            query = query.strip()
            return self.filter(
                Q(title__icontains=query)|
                Q(title__iexact=query)|
                Q(description__icontains=query)|
                Q(description__iexact=query) |
                Q(category__title__icontains=query) |
                Q(category__title__iexact=query)
            )
        return self

#managers are actually used to override database operations models are involved
class ArticleManager(models.Manager):

    def get_queryset(self):
        return ArticleQuerySet(self.model, using=self._db)

    def search(self, query): #Article.objects.search()
        return self.get_queryset().search(query)


class Category(models.Model):
    title = models.CharField(max_length=50, db_index=True, unique=True)
    slug  = models.SlugField(max_length=75, db_index=True, unique=True)
    category_logo = models.ImageField()
    body = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"

    def get_absolute_url(self):
        return reverse('blog:list-all')


class Article(models.Model):
    # associations
    author  = models.ForeignKey(settings.AUTH_USER_MODEL)
    title   = models.CharField(max_length=150, unique=True)
    description = models.CharField(max_length=200)
    slug    = models.SlugField(max_length=175, unique=True)
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default=1)
    #body    = models.TextField()
    body    = BleachField()
    posted  = models.DateTimeField(db_index=True, auto_now_add=True)

    objects = ArticleManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self): #get_absolute_url
        #return f"/restaurants/{self.slug}"
        return reverse('blog:article-view', kwargs={'slug': self.slug,
                                                'category' : self.category.slug})

profiles/models.py
from django.db import models

# Create your models here.

profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model
from django.views.generic import DetailView
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from blog.models import Category
from projects.models import Projects
import json
import urllib
from django.conf import settings
from django.contrib import messages


from django.contrib.auth.views import LoginView

User = get_user_model()

# class ProfileDetailView(DetailView):
#     template_name = 'profiles/user.html'
#
#     def get_object(self):
#         username = self.kwargs.get("username")
#         if username is None:
#             raise Http404
#         return get_object_or_404(User, username__iexact=username, is_active=True)



# class CheckBlogPermissions(UserPassesTestMixin):
#
#     permissions = ['blog.delete_article', 'blog.add_article', 'blog.change_article']
#
#     def test_func(self):
#         if self.request.user is not None and self.request.user.is_authenticated():
#             for token in self.permissions:
# CheckBlogPermissions,

class CustomLoginView(LoginView):

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        ''' Begin reCAPTCHA validation '''
        recaptcha_response = self.request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        if result['success']:
            if form.is_valid():
                return self.form_valid(form)
            else:
                return self.form_invalid(form)
        else:
            messages.error(self.request, 'Invalid reCAPTCHA. Please try again.')
            return self.form_invalid(form)



    def get_context_data(self, *args, **kwargs):
        context = super(CustomLoginView, self).get_context_data(*args, **kwargs)
        return context


class ProfileDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    template_name = 'profiles/user.html'
    permission_required = ('blog.add_article',
                           'blog.delete_article',
                           'blog.change_article',
                           'blog.add_category',
                           'blog.delete_category',
                           'blog.change_category',
                           'projects.delete_projects',
                           'projects.add_projects',
                           'projects.change_projects',
                           'about.add_about',
                           'about.delete_about',
                           'about.change_about'
                           )

    def get_object(self):
        # form = AuthenticationForm(self.request.POST)
        # if form.is_valid():
        #     ''' Begin reCAPTCHA validation '''
        #     recaptcha_response = self.request.POST.get('g-recaptcha-response')
        #     url = 'https://www.google.com/recaptcha/api/siteverify'
        #     values = {
        #         'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
        #         'response': recaptcha_response
        #     }
        #     data = urllib.parse.urlencode(values).encode()
        #     req = urllib.request.Request(url, data=data)
        #     response = urllib.request.urlopen(req)
        #     result = json.loads(response.read().decode())
        #
        #     print(recaptcha_response)
        #     print(result)
        #
        #     ''' End reCAPTCHA validation '''
        #     if result['success']:
        #         form.save()
        #         print("SUCCESS")
        #     else:
        #         print("FAIL")
        # else:
        #     print("NOT VALID")

        if self.request.user is not None and self.request.user.is_authenticated():
            return get_object_or_404(User, username__iexact=self.request.user.username, is_active=True)
        else:
            raise Http404


    def get_context_data(self, *args, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(*args, **kwargs)

        if self.request.user is not None and self.request.user.is_authenticated():
            context['user'] = self.request.user
            context['categories'] = Category.objects.all()
            context['projects'] = Projects.objects.all()
        return context

# username = self.kwargs.get("username")
#         if username is None:
#             raise Http404
#         return get_object_or_404(User, username__iexact=username, is_active=True)

profiles/templates/profiles/user.html
{% extends "base_full.html" %}

{% block head_title %} {{ block.super }} {% endblock head_title %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css">
{% endblock %}
{% block head_js %}

{% endblock %}


{% block title_content %}
   <h1 class="page-header">
     Hello,
     <small>{{ user.username }}</small>
 </h1>
{% endblock %}

{% block post_content%}


<div class="col-sm-12">
    <div class="row">
        <div class="col-md-12">
            {#{ perms.auth }#}
            <a href="{% url 'blog:article-new' %}" class="btn btn-primary btn-primary"  style="margin-bottom: 10px;"><span class="glyphicon glyphicon-check"></span> New Article</a>
            <a href="{% url 'blog:category-new' %}" class="btn btn-primary btn-primary"  style="margin-bottom: 10px;"><span class="glyphicon glyphicon-check"></span> New Category</a>
            <a href="{% url 'projects:projects-new' %}" class="btn btn-primary btn-primary"  style="margin-bottom: 10px;"><span class="glyphicon glyphicon-check"></span> New Project</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <hr/>
            <h4>About:</h4>
            <form action="{% url 'about:about-new' %}">
                <button class="btn btn-primary btn-primary"  style="margin-bottom: 10px;">
                <span class="glyphicon glyphicon-check"></span> New Biography
                </button>
            </form>
            <form action="{% url 'about:about-edit' %}">
                <button class="btn btn-primary btn-success"  style="margin-bottom: 10px;">
                <span class="glyphicon glyphicon-pencil"></span> Edit Biography
                </button>
            </form>

            <form action="{% url 'about:about-delete' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-primary btn-danger"  style="margin-bottom: 10px;">
                <span class="glyphicon glyphicon-trash"></span> Delete Biography
                </button>
            </form>

        </div>
    </div>

    <div class="table-responsive">
        <hr/>
        <h4>Articles:</h4>
        <table id="my_articles" class="table table-bordred table-striped">
        <thead>
            <th>Title</th>
            <th>Edit</th>
            <th>Delete</th>
        </thead>
        <tbody>
            {% for items in user.article_set.all %}
                <tr>
                <td>{{ items.title }}</td>
                <td>
                    <form action="{% url 'blog:article-edit' items.category.slug items.slug %}" style="display: inline;">
                        <p>
                            {#% csrf_token %#}
                            <input type="hidden" name="article" value="{{ items.slug }}" />
                            <button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" >
                                <span class="glyphicon glyphicon-pencil" data-placement="right" data-toggle="tooltip" title="Edit"></span>
                            </button>
                        </p>
                    </form>
                </td>
                <td>
                    <form action="{% url 'blog:article-delete' items.category.slug items.slug %}" method="post" style="display: inline;">
                        <p>
                            {% csrf_token %}
                            <input type="hidden" name="article" value="{{ items.slug }}" />
                            <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" >
                                <span class="glyphicon glyphicon-trash" data-placement="right" data-toggle="tooltip" title="Delete"></span>
                            </button>
                        </p>
                    </form>
                </td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>

    <div class="table-responsive">
        <hr/>
        <h4>Categories:</h4>
        <table id="my_categories" class="table table-bordred table-striped">
        <thead>
            <th>Title</th>
            <th>Edit</th>
            <th>Delete</th>
        </thead>
        <tbody>
            {% for items in categories %}
                {% if items.slug != "nocat" %}
                <tr>
                <td>{{ items.title }}</td>
                <td>
                    <form action="{% url 'blog:category-edit' items.slug %}" style="display: inline;">
                        <p>
                            {#% csrf_token %#}
                            <input type="hidden" name="category" value="{{ items.slug }}" />
                            <button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" >
                                <span class="glyphicon glyphicon-pencil" data-placement="right" data-toggle="tooltip" title="Edit"></span>
                            </button>
                        </p>
                    </form>
                </td>
                <td>
                    <form action="{% url 'blog:category-delete' items.slug %}" method="post" style="display: inline;">
                        <p>
                            {% csrf_token %}
                            <input type="hidden" name="category" value="{{ items.slug }}" />
                            <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" >
                                <span class="glyphicon glyphicon-trash" data-placement="right" data-toggle="tooltip" title="Delete"></span>
                            </button>
                        </p>
                    </form>
                </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
        </table>
    </div>

    <div class="table-responsive">
        <hr/>
        <h4>Projects:</h4>
        <table id="my_projects" class="table table-bordred table-striped">
        <thead>
            <th>Title</th>
            <th>Edit</th>
            <th>Delete</th>
        </thead>
        <tbody>
            {% for items in projects %}
                {% if items.slug != "nocat" %}
                <tr>
                <td>{{ items.title }}</td>
                <td>
                    <form action="{% url 'projects:projects-edit' items.slug %}" style="display: inline;">
                        <p>
                            {#% csrf_token %#}
                            <input type="hidden" name="category" value="{{ items.slug }}" />
                            <button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" >
                                <span class="glyphicon glyphicon-pencil" data-placement="right" data-toggle="tooltip" title="Edit"></span>
                            </button>
                        </p>
                    </form>
                </td>
                <td>
                    <form action="{% url 'projects:projects-delete' items.slug %}" method="post" style="display: inline;">
                        <p>
                            {% csrf_token %}
                            <input type="hidden" name="category" value="{{ items.slug }}" />
                            <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" >
                                <span class="glyphicon glyphicon-trash" data-placement="right" data-toggle="tooltip" title="Delete"></span>
                            </button>
                        </p>
                    </form>
                </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
        </table>
    </div>

</div>
{% endblock %}

{% block custom_js %}
<script>
    $(document).ready(function(){
        $("#my_articles #checkall").click(function () {
            if ($("#my_articles #checkall").is(':checked')) {
                $("#my_articles input[type=checkbox]").each(function () {
                    $(this).prop("checked", true);
                });
            } else {
                $("#my_articles input[type=checkbox]").each(function () {
                    $(this).prop("checked", false);
            });
        }
    });


    $("[data-toggle=tooltip]").tooltip();
});

</script>

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" class="init">
        $(document).ready(function(){
            $('#my_articles').DataTable();
        });
    </script>
    <script type="text/javascript" class="init">
        $(document).ready(function(){
            $('#my_categories').DataTable();
        });
    </script>
    <script type="text/javascript" class="init">
        $(document).ready(function(){
            $('#my_projects').DataTable();
        });
    </script>

{% endblock %}