andreivscompsci/urls.py
#from django.conf.urls import url
#from django.contrib import admin

#urlpatterns = [
#    url(r'^admin/', admin.site.urls),
#]
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView

from django.conf import settings
from django.conf.urls.static import static
from profiles.views import CustomLoginView

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', TemplateView.as_view(template_name='home_blog.html'), name='home'),
    #url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    #url(r'^test/$', TemplateView.as_view(template_name='test.html'), name='test'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^profile/', include('profiles.urls', namespace='profiles')),
    #url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^login/$', CustomLoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page='/'), name='logout'),

    url(r'^summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url

from .views import (
    ArticleListView,
    AllArticleListView,
    ArticleDetailView,
    ArticleDeleteView,
    ArticleUpdateView,
    ArticleCreateView,

    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView
)

urlpatterns = [
    #url(r'^$', ArticleListView.as_view(), name='list-all'),
    url(r'^$', AllArticleListView.as_view(), name='list-all'),
    url(r'^new-article/$', ArticleCreateView.as_view(), name='article-new'),
    url(r'^new-category/$', CategoryCreateView.as_view(), name='category-new'),
    url(r'^(?P<slug>[-\w]+)/update/$', CategoryUpdateView.as_view(), name='category-edit'),
    url(r'^(?P<slug>[-\w]+)/delete/$', CategoryDeleteView.as_view(), name='category-delete'),
    url(r'^(?P<category>[-\w]+)/$', ArticleListView.as_view(), name='list-specific'),
    url(r'^(?P<category>[-\w]+)/page/(?P<page>\d+)/$', ArticleListView.as_view(), name='list-page'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/update/$', ArticleUpdateView.as_view(), name='article-edit'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/delete/$', ArticleDeleteView.as_view(), name='article-delete'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$', ArticleDetailView.as_view(), name='article-view')
]

search/urls.py
from django.conf.urls import url
from .views import SearchArticleListView


urlpatterns = [
    #url(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name='detail')
    url(r'^$', SearchArticleListView.as_view(), name='index')
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from django.views.generic import ListView
from blog.models import Article

# user = context['user']
# query = self.request.GET.get('q')
# items_exists = Item.objects.filter(user=user).exits()

# Create your views here.
class SearchArticleListView(ListView):
    template_name = "search/search_results.html"

    def get_queryset(self):
    #def get_context_data(self, *args, **kwargs):
    #    context = super(SearchArticleListView, self).get_context_data(*args, **kwargs)
        query = self.request.GET.get('q')
        #print("Query", query)
        if query:
            qs = Article.objects.all().search(query)
        else:
            qs = Article.objects.none()
        return qs
        #if qs.exists():
        #    context['articles'] = qs
        #return context

search/templates/search/search_results.html
{% extends "base_post.html" %}

{% block head_title %} {{ block.super }} {% endblock head_title %}

{% block title_content %}
     <h1 class="page-header">
         Search results
         <small>List of articles</small>
     </h1>
{% endblock %}

{% block post_content %}
    <p>
        {% if object_list %}
            {% for art in object_list %}
                <h2>
                    <a href="#">{{ art.title }}</a>
                    </h2>
                    <p class="lead">
                        by <a href="{% url "about:biography" %}">{{ art.author.first_name }} {{ art.author.last_name }}</a>
                    </p>
                    <p><span class="glyphicon glyphicon-time"></span> Posted on {{ art.posted | date:"M d, Y" }}</p>
                    <p>
                        {{ art.description|truncatechars:200|linebreaks }}
                    </p>
                    <a class="btn btn-primary" href="{% url "blog:article-view" category=art.category.slug slug=art.slug %}">
                        Read More
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                    <hr>
            {% endfor %}
        {% else %}
            <h2>No results found</h2>
        {% endif %}
    </p>
{% endblock %}