andreivscompsci/urls.py
#from django.conf.urls import url
#from django.contrib import admin

#urlpatterns = [
#    url(r'^admin/', admin.site.urls),
#]
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView

from django.conf import settings
from django.conf.urls.static import static
from profiles.views import CustomLoginView

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', TemplateView.as_view(template_name='home_blog.html'), name='home'),
    #url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    #url(r'^test/$', TemplateView.as_view(template_name='test.html'), name='test'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^profile/', include('profiles.urls', namespace='profiles')),
    #url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^login/$', CustomLoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page='/'), name='logout'),

    url(r'^summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url

from .views import (
    ArticleListView,
    AllArticleListView,
    ArticleDetailView,
    ArticleDeleteView,
    ArticleUpdateView,
    ArticleCreateView,

    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView
)

urlpatterns = [
    #url(r'^$', ArticleListView.as_view(), name='list-all'),
    url(r'^$', AllArticleListView.as_view(), name='list-all'),
    url(r'^new-article/$', ArticleCreateView.as_view(), name='article-new'),
    url(r'^new-category/$', CategoryCreateView.as_view(), name='category-new'),
    url(r'^(?P<slug>[-\w]+)/update/$', CategoryUpdateView.as_view(), name='category-edit'),
    url(r'^(?P<slug>[-\w]+)/delete/$', CategoryDeleteView.as_view(), name='category-delete'),
    url(r'^(?P<category>[-\w]+)/$', ArticleListView.as_view(), name='list-specific'),
    url(r'^(?P<category>[-\w]+)/page/(?P<page>\d+)/$', ArticleListView.as_view(), name='list-page'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/update/$', ArticleUpdateView.as_view(), name='article-edit'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/delete/$', ArticleDeleteView.as_view(), name='article-delete'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$', ArticleDetailView.as_view(), name='article-view')
]

blog/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django_bleach.models import BleachField


class ArticleQuerySet(models.query.QuerySet):
    def search(self, query): #Article.objects.all().search(query) #Article.objects.filter(something).search()
        if query:
            query = query.strip()
            return self.filter(
                Q(title__icontains=query)|
                Q(title__iexact=query)|
                Q(description__icontains=query)|
                Q(description__iexact=query) |
                Q(category__title__icontains=query) |
                Q(category__title__iexact=query)
            )
        return self

#managers are actually used to override database operations models are involved
class ArticleManager(models.Manager):

    def get_queryset(self):
        return ArticleQuerySet(self.model, using=self._db)

    def search(self, query): #Article.objects.search()
        return self.get_queryset().search(query)


class Category(models.Model):
    title = models.CharField(max_length=50, db_index=True, unique=True)
    slug  = models.SlugField(max_length=75, db_index=True, unique=True)
    category_logo = models.ImageField()
    body = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"

    def get_absolute_url(self):
        return reverse('blog:list-all')


class Article(models.Model):
    # associations
    author  = models.ForeignKey(settings.AUTH_USER_MODEL)
    title   = models.CharField(max_length=150, unique=True)
    description = models.CharField(max_length=200)
    slug    = models.SlugField(max_length=175, unique=True)
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default=1)
    #body    = models.TextField()
    body    = BleachField()
    posted  = models.DateTimeField(db_index=True, auto_now_add=True)

    objects = ArticleManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self): #get_absolute_url
        #return f"/restaurants/{self.slug}"
        return reverse('blog:article-view', kwargs={'slug': self.slug,
                                                'category' : self.category.slug})

blog/forms.py
from django import forms
from .models import Article, Category
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class ArticleCreateForm(forms.ModelForm):
    #email           = forms.EmailField()
    #category         = forms.CharField(required=False, validators=[validate_category])
    #body = forms.CharField(widget=SummernoteWidget())
    description = forms.CharField(
        max_length = 150,
        widget = forms.Textarea
    )

    class Meta:
        model = Article
        fields = [
            'title',
            'description',
            'slug',
            'category',
            'body',
        ]
        widgets = {
            'body' : SummernoteWidget()
        }
    # def clean_name(self):
    #     name = self.cleaned_data.get("name")
    #     if name == "Hello":
    #         raise forms.ValidationError("Not a valid name")
    #     return name


class CategoryCreateForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = [
            'title',
            'slug',
            'category_logo',
            'body'
        ]

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Article, Category
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.http import Http404
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse_lazy
from .forms import ArticleCreateForm, CategoryCreateForm
from django.http import HttpResponseNotAllowed
from django.contrib.auth.mixins import PermissionRequiredMixin


class AllArticleListView(ListView):

    template_name = "blog/all_articles.html"

    def get_queryset(self):
        queryset = Category.objects.all()
        return queryset


class ArticleListView(ListView):
    template_name = 'blog/article_list.html'
    paginate_by = 4

    def get_context_data(self, *args, **kwargs):
        context = super(ArticleListView, self).get_context_data(*args, **kwargs)

        category_slug = self.kwargs.get("category")
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            if category:
                context['category'] = category.title
                context['cat_slug'] = category.slug
            else:
                raise Http404
        return context

    def get_queryset(self):
        #print(self.kwargs)
        category_slug = self.kwargs.get("category")
        if category_slug:
            category = Category.objects.filter(slug=category_slug).exists();
            if category:
                #print("Category slug: ", category_slug)
                queryset = Article.objects.filter(
                    category__slug__iexact=category_slug
                ).order_by('-posted')
            else:
                raise Http404
        return queryset

class ArticleDetailView(DetailView):

    def get_queryset(self):
        #print(self.kwargs)
        return Article.objects.filter(category__slug=self.kwargs['category'], slug=self.kwargs['slug'])


class ArticleCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    form_class = ArticleCreateForm
    template_name = 'blog/article_form.html'
    permission_required = 'blog.add_article'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(ArticleCreateView, self).form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):

    form_class = ArticleCreateForm
    template_name = 'blog/article_form.html'
    permission_required = 'blog.change_article'

    def get_queryset(self):
        return Article.objects.filter(author=self.request.user)


class ArticleDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):

    model = Article
    success_url = reverse_lazy('profiles:index')
    permission_required = 'blog.delete_article'

    def get(self, *args, **kwargs):
        # return self.post(*args, **kwargs)
        return HttpResponseNotAllowed(['POST'])

# Category views

class CategoryCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    form_class = CategoryCreateForm
    template_name = 'blog/category_form.html'
    permission_required = 'blog.add_category'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CategoryCreateView, self).form_valid(form)


class CategoryUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    form_class = CategoryCreateForm
    template_name = 'blog/category_form.html'
    permission_required = 'blog.change_category'

    def get_queryset(self):
        return Category.objects.all()


class CategoryDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):

    model = Category
    success_url = reverse_lazy('profiles:index')
    permission_required = 'blog.delete_category'

    def get(self, *args, **kwargs):
        #return self.post(*args, **kwargs)
        return HttpResponseNotAllowed(['POST'])


        #def get_object(self, queryset=None):
        #obj = super(ArticleDeleteView, self).get_object()
        #print("Obj owner: ", obj.owner)
        #print("Obj request user: ", self.request.user)
        #if not obj.author == self.request.user:
        #    raise Http404
        #account = Article.objects.get(id=obj.article.id)
        #return obj


            # class ArticleDeleteView(LoginRequiredMixin, DeleteView):
#
#     model = Article
#
#     def get_queryset(self):
#         qs = super(ArticleDeleteView, self).get_queryset()
#         print(self.request.pk)
#         return qs.filter(pk=self.request.pk)

#def post_delete(request, id=None):
#    instance = get_object_or_404(Article, id=id)
#    instance.delete()
#    messages.success(request, "Successfully deleted")
#    return redirect("posts:list")




# def delete_song(request, album_id, song_id):
#     album = get_object_or_404(Album, pk=album_id)
#     song = Song.objects.get(pk=song_id)
#     song.delete()
#     return render(request, 'music/detail.html', {'album': album})

#
# from django.views.generic.base import View
#
# class DeleteView(View):
#     def post(self, request *args, **kwargs):
#         article = get_object_or_404(id=request.POST['article_id'])
#         # perform some validation,
#         # like can this user delete this article or not, etc.
#         # if validation is successful, delete the article
#         article.delete()
#         return HttpResponseRedirect('/')
# Your template should be like this:
#
# <form action="/url/to/delete/view/" method="POST">
#     {% csrf_token %}
#     <input type="hidden" value="{{ article.id }}">
#     <input type="submit" value="Delete">
# </form>

blog/templates/blog/all_articles.html
{% extends "base_post.html" %}

{% block head_title %} All articles | {{ block.super }} {% endblock head_title %}

{% block title_content %}
     <h1 class="page-header">
         All Categories
          <small>List of articles</small>
     </h1>
{% endblock %}

{% block post_content %}
        {#% load showblog_entries %#}
        {% for category in object_list %}
            {% if category.slug != "nocat" %}
            {#% if category.slug != "nocat" %#}

            {#% show_articles category.slug %#}
            {#% endif %#}
                <div class="col-md-6">
                <!--<div class="col-md-6">-->
                <div class="thumbnail">
                            <!--<img src="http://placehold.it/500x400" alt="">-->
                    <img src="{{ category.category_logo.url }}" alt="{{ category.slug }}" style="width: 265px; height: 145px;" >
                    <div class="caption">
                        <h4>{{ category.title }}</h4>
                        <div style="min-height: 100px; max-height: 100px;">
                        {{ category.body|truncatechars:150|linebreaks }}
                        </div>
                        <p><a href="{% url "blog:list-specific" category=category.slug %}" class="btn btn-info btn-xs" role="button">List articles</a></p>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}

{% endblock %}

blog/templates/blog/all_articles_bk.html
{% extends "base.html" %}

{% block head_title %} All articles | {{ block.super }} {% endblock head_title %}

{% block title_content %}
    <h1>All categories</h1>
    <p>List of articles</p>
{% endblock %}

{% block post_content %}
    <p>
        {% load showblog_entries %}
        {% for category in object_list %}
            <h1>{{category}}</h1>
            {% show_articles category.slug %}
        {% endfor %}
    </p>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends "base_post.html" %}

{% block head_title %} {{ object.title }} || {{ block.super }} {% endblock head_title %}

{% block meta_tags %}
<meta name="description" content="{{ object.description|truncatechars:200|linebreaks|striptags }}"/>
{% endblock %}

{% block title_content %}
     <h1 class="page-header">
         {{ object.title }}
    </h1>
{% endblock %}

{% block post_content %}
    <!-- Blog post -->
    <small>
        <span class="glyphicon glyphicon-time"></span> Posted on {{ object.posted | date:"M d, Y" }}
            by <a href='{% url "about:biography" %}'>{{  object.author.first_name }} {{ object.author.last_name }}</a>
    </small>
    <p>
        {% load bleach_tags %}
        {{ object.body | bleach }}
    </p>


    <div id="disqus_thread"></div>
    <script>

    var disqus_config = function () {
        var PAGE_URL = 'https://andreivscompsci.ca{% url "blog:article-view" category=object.category.slug slug=object.slug %}';
        var PAGE_IDENTIFIER = '{{ object.slug}}';
        this.page.url = PAGE_URL;
        this.page.identifier = PAGE_IDENTIFIER;
    };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://andreivscompsci.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

{% endblock %}

{% block custom_js %}
    <script id="dsq-count-scr" src="//andreivscompsci.disqus.com/count.js" async></script>
{% endblock %}

blog/templates/blog/article_detail_bk.html
{% extends "base.html" %}

{% block head_title %} Welcome | {{ block.super }} {% endblock head_title %}

{% block title_content %}
    <h1>All categories</h1>
    <p>List of articles</p>
{% endblock %}

{% block post_content %}
    <p>
    <h1>{{ object.title }} <small> {{ object.category }}</small></h1>
    <p>{{ object.body }}</p>
    <p><small>Posted: {{ object.posted }}</small></p>
    </p>
{% endblock %}

blog/templates/blog/article_form.html
{% extends "base.html" %}

{% block head_title %} {{ block.super }} {% endblock head_title %}

{% block custom_css %}

{% endblock %}

{% block title_content %}
    <h1 class="page-header">New article
     <small>New/Edit</small>
    </h1>
{% endblock %}

{% block post_content%}
      {% include 'snippets/form-snippet.html' with form=form %}
{% endblock %}

{% block custom_js %}
    <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.6.4/js/froala_editor.min.js'></script>
{% endblock %}

blog/templates/blog/article_list.html
{% extends "base.html" %}

{% block head_title %} Archive | {{ block.super }} {% endblock head_title %}

{% block title_content %}
    <h1 class="page-header">
     {{ category }}
    <small>List of articles</small>
    </h1>
{% endblock %}

{% block post_content %}
    <p>
        <!--{#% for obj in object_list %}
            <h3><a href='{#% url "blog:article-view" category=obj.category.slug slug=obj.slug %#}'>{#{ obj.title }#}</a></h3>
        {#% endfor %#}-->

        {#% load showblog_entries %#}
        {#% show_articles  cat_slug  %#}


        {% load bleach_tags %}
        {% for art in object_list %}
            <h2>
                <a href="{% url "blog:article-view" category=art.category.slug slug=art.slug %}">{{ art.title }}</a>
            </h2>
            <p class="lead">
                by <a href="{% url "about:biography" %}">{{ art.author.first_name }} {{ art.author.last_name }}</a>
            </p>
            <p><span class="glyphicon glyphicon-time"></span> Posted on {{ art.posted | date:"M d, Y" }}</p>
            <p>
                {{ art.description|truncatechars:200|linebreaks }}
            </p>
            <a class="btn btn-primary" href="{% url "blog:article-view" category=art.category.slug slug=art.slug %}">
                Read More
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
            <hr>
        {% endfor %}


        {% if is_paginated %}
        <span class="currentpage">
        {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        <ul class="pager">
            {% if page_obj.has_previous %}
            <li class="previous">
                <a href="{% url "blog:list-page" category=cat_slug page=page_obj.previous_page_number %}">&larr; Newer</a>
            </li>
            {% endif %}

            {% if page_obj.has_next %}
            <li class="next">
                <a href="{% url "blog:list-page" category=cat_slug page=page_obj.next_page_number %}">Older &rarr;</a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </p>
{% endblock %}

blog/templates/blog/category_form.html
{% extends "base.html" %}

{% block head_title %} {{ block.super }} {% endblock head_title %}

{% block custom_css %}
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.6.4/css/froala_editor.min.css' rel='stylesheet' type='text/css' />
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.6.4/css/froala_style.min.css' rel='stylesheet' type='text/css' />
<script src="//cdn.ckeditor.com/4.7.1/basic/ckeditor.js"></script>
{% endblock %}

{% block title_content %}
    <h1 class="page-header"> New category
     <small>New/Edit</small>
    </h1>
{% endblock %}

{% block post_content%}
      {% include 'snippets/form-snippet-file.html' with form=form %}
{% endblock %}

{% block custom_js %}
    <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.6.4/js/froala_editor.min.js'></script>
{% endblock %}

blog/templates/blog/show_blog_categories.html
{% for cat in categories %}
    {% if cat.slug != "nocat" %}
<li><a href='{% url "blog:list-specific" cat.slug %}'>{{ cat }}</a></li>
    {% endif %}
{% endfor %}

blog/templates/blog/show_blog_categories_widget.html
{#{ num_art_in_cat }#}
{% for cat in num_art_in_cat %}
    {% if cat.slug != "nocat" %}
    <a href='{% url "blog:list-specific" cat.slug %}' class="list-group-item">{{ cat.title }} <span class="badge">{{ cat.article__title__count }} </span></a>
    {% endif %}
{% endfor %}

blog/templates/blog/show_blog_entries.html
{% load bleach_tags %}
{% for art in articles %}
    <h2>
        <a href="{% url "blog:article-view" category=art.category.slug slug=art.slug %}">{{ art.title }}</a>
    </h2>
    <p class="lead">
        by <a href="{% url "about:biography" %}">{{ art.author.first_name }} {{ art.author.last_name }}</a>
    </p>
    <p><span class="glyphicon glyphicon-time"></span> Posted on {{ art.posted | date:"M d, Y" }}</p>
                <!--
                <hr>
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <hr>
                -->
    <p>
        {#{ art.body|safe|truncatewords:"50"|linebreaks }#}
        {{ art.description|truncatechars:200|linebreaks }}
    </p>
    <a class="btn btn-primary" href="{% url "blog:article-view" category=art.category.slug slug=art.slug %}">
        Read More
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
    <hr>

{% endfor %}

blog/templates/blog/show_blog_entries_bk.html
{% for art in articles %}
<li><a href='/blog/{{art.category.slug}}/{{art.slug}}'>{{ art.title }}</a></li>
{% endfor %}