andreivscompsci/urls.py
#from django.conf.urls import url
#from django.contrib import admin

#urlpatterns = [
#    url(r'^admin/', admin.site.urls),
#]
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView

from django.conf import settings
from django.conf.urls.static import static
from profiles.views import CustomLoginView

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', TemplateView.as_view(template_name='home_blog.html'), name='home'),
    #url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    #url(r'^test/$', TemplateView.as_view(template_name='test.html'), name='test'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^profile/', include('profiles.urls', namespace='profiles')),
    #url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^login/$', CustomLoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page='/'), name='logout'),

    url(r'^summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url

from .views import (
    ArticleListView,
    AllArticleListView,
    ArticleDetailView,
    ArticleDeleteView,
    ArticleUpdateView,
    ArticleCreateView,

    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView
)

urlpatterns = [
    #url(r'^$', ArticleListView.as_view(), name='list-all'),
    url(r'^$', AllArticleListView.as_view(), name='list-all'),
    url(r'^new-article/$', ArticleCreateView.as_view(), name='article-new'),
    url(r'^new-category/$', CategoryCreateView.as_view(), name='category-new'),
    url(r'^(?P<slug>[-\w]+)/update/$', CategoryUpdateView.as_view(), name='category-edit'),
    url(r'^(?P<slug>[-\w]+)/delete/$', CategoryDeleteView.as_view(), name='category-delete'),
    url(r'^(?P<category>[-\w]+)/$', ArticleListView.as_view(), name='list-specific'),
    url(r'^(?P<category>[-\w]+)/page/(?P<page>\d+)/$', ArticleListView.as_view(), name='list-page'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/update/$', ArticleUpdateView.as_view(), name='article-edit'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/delete/$', ArticleDeleteView.as_view(), name='article-delete'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$', ArticleDetailView.as_view(), name='article-view')
]

templates/snippets/css-home.html
<style>
    body {
        padding-top: 70px; /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    currentpage {
        text-align:left;
    }
</style>

templates/snippets/css-main.html
<!-- Latest compiled and minified CSS -->
{% load staticfiles %}
    <link rel="icon" href="{% static 'logo.png' %}" />

<link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
      crossorigin="anonymous">

<link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">


<style>
    html {
        position: relative;
        min-height: 100%;
    }
    body {
        /* Margin bottom by footer height */
        margin-bottom: 170px;
    }
    .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        /* Set the fixed height of the footer here */
        height: 150px;
        background-color: #101010;
    }
</style>

<style>
    body {
        padding-top: 50px;
    }
    .navbar{
        border-radius: 0;
        background-image: none;
    }
    .navbar-brand {
        padding-top: 0px;
    }

    @media (max-width: 500px) {
        .navbar-text {
            display: none;
        }
    }
    .textLogo {
       font-family: 'Press Start 2P', cursive;
    }
</style>

templates/snippets/css-post.html
<style>
    body {
        padding-top: 70px; /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
</style>

templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
{% load staticfiles %}
    <link rel="icon" href="{% static 'logo.png' %}" />

<link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
      crossorigin="anonymous">

<link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">

<style>
    html {
        position: relative;
        min-height: 100%;
    }
    body {
        /* Margin bottom by footer height */
        margin-bottom: 170px;
    }
    .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        /* Set the fixed height of the footer here */
        height: 150px;
        background-color: #333366;
    }
</style>

<style>
    body {
        padding-top: 50px;
    }

    .navbar{
        border-radius: 0;
        background-image: none;
    }

    .navbar-brand {
        padding-top: 0px;
    }

    @media (max-width: 500px) {
        .navbar-text {
            display: none;
        }
    }

    .textLogo {
       font-family: 'Press Start 2P', cursive;
    }

    .titleTop {
        background-color: #FFCF75;
        height: 300px;
    }
    .page-content-header {
        padding-top: 50px;
        background-color: #FF9933;
        min-height: 200px;
    }

</style>

templates/snippets/footer-snippet.html
    <footer class="footer">
        <div class="container">
            <p style="margin-top: 10px;">
                <!--<li><a href='{#% url "contact" %#}'>Contact Me</a></li>-->
                {% load staticfiles %}

                    <a href="https://github.com/andreivscompsci"><img src="{% static 'GitHub-Mark/PNG/GitHub-Mark-Light-64px.png' %}" alt="Github"></a>
                    <a href="mailto:andreivscompsci@gmail.com?Subject=BlogMsg" target="_top"><img src="{% static 'email.png' %}" alt="Email"></a>

            </p>
            <p class="text-muted"> © 2017 Andrei Vs CompSci </p>
        </div>
    </footer>

templates/snippets/form-snippet-file.html
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form method='POST' enctype="multipart/form-data"> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Save</button>
</form>
 <!--enctype="multipart/form-data"-->

templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form method='POST'> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Save</button>
</form>
 <!--enctype="multipart/form-data"-->

templates/snippets/home-blog-post.html
                <!-- First Blog Post -->
                <h2>
                    <a href="#">Blog Post Title</a>
                </h2>
                <p class="lead">
                    by <a href="index.php">Start Bootstrap</a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
                <hr>
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, veritatis, tempora, necessitatibus inventore nisi quam quia repellat ut tempore laborum possimus eum dicta id animi corrupti debitis ipsum officiis rerum.</p>
                <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
                <hr>

templates/snippets/js.html
 <script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
    crossorigin="anonymous">
 </script>
 <script>

     $(document).ready(function() {
         $('li.active').removeClass('active');
         $('a[href="' + location.pathname + '"]').closest('li').addClass('active');
     });

 </script>

templates/snippets/nav-blog.html
 <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

templates/snippets/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container"> 
        <div class="navbar-header">
    
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
            </button>

            <a class="navbar-brand" rel="home" href='{% url "home" %}'>
                {% load staticfiles %}
                <img src="{% static 'logo.png' %}" height="45" width="45" alt="AndreiVsWorld">
            </a>
            <p class="navbar-text navbar-left"><span class="textLogo">AndreiVsCompSci</span></p>

        </div>
        
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <!--data-toggle="tab" -->
                <li><a  href='{% url "home" %}'>Home</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Blog <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href='{% url "blog:list-all" %}'>All</a></li>
                            <!--<li><a href="#">General</a></li>-->
                            {% load showblog_categories %}
                            {% show_categories %}
                        </ul>
                    </li>
                    <li><a href='{% url "projects:index" %}'>Projects</a></li>
                    <li><a href='{% url "about:biography" %}'>About</a></li>
                </ul>
            <ul class="nav navbar-nav navbar-right">
                <!--<li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->

                {% if user.is_authenticated %}
                     <li><a href="{% url "profiles:index" %}"><span class="glyphicon glyphicon-user"></span>My Profile</a></li>
                {% endif %}
                <li>
                    {% if user.is_authenticated %}
                        <a href="{% url "logout" %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a>
                    {% else %}
                        <a href="{% url "login" %}"><span class="glyphicon glyphicon-log-in"></span>Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/snippets/side-widget.html
 <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <form method="GET" action="/search"  class="form-inline">
                        <span class="input-group-btn">
                            <input type="text" placeholder="Search..." name="q" value="{{ request.GET.q }}" class="form-control">
                                <button class="btn btn-default" type="submit">
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </span>
                        </form>

                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="list-group">
                            {% load showblog_categories %}
                            {% show_categories_widget %}
                            </div>
                        </div>
                    </div>
                </div>

            </div>